### ISSUE TITLE
Open Community Survey Close out

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/governance#66]
### Overview
Bonnie needs to close out the open community survey

### Action Items
9 steps process to close this project

**Comment by ExperimentsInHonesty** [comment]
- [ ] Finish [OCS One sheet] https://github.com/hackforla/product-management/issues/76(https://docs.google.com/document/d/1oiCWwN0aUZEYXa_ir2n0l6D47fkXqFEQFkh4YMW3CjY/edit)
    - [ ] Update tracker re one sheet
   - [ ] It needs a tiny amount editing to be finished with wording
   - [ ] Be clear which partner for which initiative (super by design #1)
- [ ] Revise what it says on the website because its overly focused on the current initiative
- [ ] Make a separate project card for the Empowerla one
- [ ] Finish design work on https://github.com/hackforla/website/issues/632 | https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=5140%3A26436
